//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanici()
        {
            this.satis = new HashSet<satis>();
        }
    
        public int kullanici_id { get; set; }
        [Display(Name="Kullanıcı Adı")]
        [Required(ErrorMessage ="Kullanıcı Adı alanı boş geçilemez")]
        public string k_kullaniciadi { get; set; }
        [Display(Name = "Parola")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Parola alanı boş geçilemez")]
        public string k_parola { get; set; }
        [Display(Name = "Adı")]
        [Required(ErrorMessage = "Adı alanı boş geçilemez")]
        public string k_adi { get; set; }
        [Display(Name = "Soyadı")]
        [Required(ErrorMessage = "Soyadı alanı boş geçilemez")]
        public string k_soyadi { get; set; }
        [Display(Name = "E-posta")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
        ErrorMessage = "Lütfen uygun formatta e-mail adresi giriniz.")]
        [Required(ErrorMessage = "E-posta alanı boş geçilemez")]
        public string k_eposta { get; set; }
        [Display(Name = "Telefon")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
        ErrorMessage = "Uygun formatta telefon numarası giriniz.")]
        [Required(ErrorMessage = "Telefon alanı boş geçilemez")]

        public string k_telefon { get; set; }
        [Display(Name = "Durum")]
        [Required(ErrorMessage = "Durum alanı boş geçilemez")]
        public bool k_durum { get; set; }
        [Display(Name = "Rol Adı")]
        [Required(ErrorMessage = "Rol Adı alanı boş geçilemez")]
        public int rol_id { get; set; }
    
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis> satis { get; set; }
    }
}
