//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis_log_ins_del
    {
        public int slid_id { get; set; }
        public int satis_id { get; set; }
        public Nullable<System.DateTime> s_tarih { get; set; }
        public string s_durum { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public System.DateTime islem_tarihi { get; set; }
        public string islem_turu { get; set; }
        public string islem_ip { get; set; }
    }
}
