//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis_maddeleri
    {
        public int sm_id { get; set; }
        public double si_miktar { get; set; }
        public double si_fiyat { get; set; }
        public Nullable<double> si_iskonto { get; set; }
        public int satis_id { get; set; }
        public int urun_id { get; set; }
    
        public virtual satis satis { get; set; }
        public virtual urun urun { get; set; }
    }
}
