//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class stok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stok()
        {
            this.urun = new HashSet<urun>();
        }
    
        public int stok_id { get; set; }
        [Display(Name = "Stok Adedi")]
        public int s_adedi { get; set; }
        public System.DateTime s_giris_tarihi { get; set; }
        [Display(Name = "Stok Giriş Tarihi")]
        public Nullable<System.DateTime> s_bitis_tarihi { get; set; }
        [Display(Name = "Stok Bitiş Tarihi")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urun> urun { get; set; }
    }
}
