//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_log_up
    {
        public int stlu_ip { get; set; }
        public Nullable<int> eski_s_adedi { get; set; }
        public Nullable<int> yeni_s_adedi { get; set; }
        public Nullable<System.DateTime> eski_s_giris_tarihi { get; set; }
        public Nullable<System.DateTime> yeni_s_giris_tarihi { get; set; }
        public Nullable<System.DateTime> eski_s_bitis_tarihi { get; set; }
        public Nullable<System.DateTime> yeni_s_bitis_tarihi { get; set; }
        public System.DateTime islem_tarihi { get; set; }
        public string islem_ip { get; set; }
    }
}
