//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun()
        {
            this.satis_maddeleri = new HashSet<satis_maddeleri>();
        }
        
        public int urun_id { get; set; }
        [Display(Name = "Ürün Adı")]
        public string u_adi { get; set; }
        [Display(Name = "Barkodu")]
        public string u_barkodu { get; set; }
        [Display(Name = "Üretim Tarihi")]
        public Nullable<System.DateTime> u_uretim_tarihi { get; set; }
        [Display(Name = "Tüketim Tarihi")]
        public Nullable<System.DateTime> u_tuketim_tarihi { get; set; }
        [Display(Name = "Fiyatı")]
        public double u_fiyat { get; set; }
        [Display(Name = "Ağırlık")]
        public Nullable<double> u_agirlik { get; set; }
        [Display(Name = "Renk")]
        public string u_rengi { get; set; }
        [Display(Name = "Marka Adı")]
        public int marka_id { get; set; }
        [Display(Name = "Kategori Adı")]
        public int kategori_id { get; set; }
        [Display(Name = "Stok Adedi")]
        public int stok_id { get; set; }

     
        public virtual kategori kategori { get; set; }
       
        public virtual marka marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_maddeleri> satis_maddeleri { get; set; }
        
        public virtual stok stok { get; set; }
        
       // public List<SelectListItem> KategoriListesi { get; set; }
    
        //public List<SelectListItem> MarkaListesi { get; set; }
    }
}
