//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun_log_up
    {
        public int ulu_id { get; set; }
        public string eski_u_adi { get; set; }
        public string yeni_u_adi { get; set; }
        public string eski_u_barkodu { get; set; }
        public string yeni_u_barkodu { get; set; }
        public Nullable<System.DateTime> eski_u_uretim_tarihi { get; set; }
        public Nullable<System.DateTime> yeni_u_uretim_tarihi { get; set; }
        public Nullable<System.DateTime> eski_u_tuketim_tarihi { get; set; }
        public Nullable<System.DateTime> yeni_u_tuketim_tarihi { get; set; }
        public Nullable<double> eski_u_fiyat { get; set; }
        public Nullable<double> yeni_u_fiyat { get; set; }
        public Nullable<double> eski_u_agirlik { get; set; }
        public Nullable<double> yeni_u_agirlik { get; set; }
        public string eski_u_rengi { get; set; }
        public string yeni_u_rengi { get; set; }
        public Nullable<int> eski_marka_id { get; set; }
        public Nullable<int> yeni_marka_id { get; set; }
        public Nullable<int> eski_kategori_id { get; set; }
        public Nullable<int> yeni_kategori_id { get; set; }
        public Nullable<int> eski_stok_id { get; set; }
        public Nullable<int> yeni_stok_id { get; set; }
        public System.DateTime islem_tarihi { get; set; }
        public string islem_ip { get; set; }
    }
}
