//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalımNet.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun_log_ins_del
    {
        public int ulid_id { get; set; }
        public int urun_id { get; set; }
        public string u_adi { get; set; }
        public string u_barkodu { get; set; }
        public Nullable<System.DateTime> u_uretim_tarihi { get; set; }
        public Nullable<System.DateTime> u_tuketim_tarihi { get; set; }
        public Nullable<double> u_fiyat { get; set; }
        public Nullable<double> u_agirlik { get; set; }
        public string u_rengi { get; set; }
        public Nullable<int> marka_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> stok_id { get; set; }
        public System.DateTime islem_tarihi { get; set; }
        public string islem_turu { get; set; }
        public string islem_ip { get; set; }
    }
}
